# Generated by Django 4.2.6 on 2023-10-22 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name1', to='secret_santa.name')),
                ('name2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name2', to='secret_santa.name')),
            ],
        ),
    ]
