# Generated by Django 4.2.6 on 2023-10-22 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rule',
            name='name1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name1_rules', to='secret_santa.name'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='name2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name2_rules', to='secret_santa.name'),
        ),
    ]
